
version: 3

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: course_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
